apiVersion: apps/v1
kind: Deployment
metadata: { name: myapp-blue, labels: { app: myapp, color: blue } }
spec:
  replicas: 1
  selector: { matchLabels: { app: myapp, color: blue } }
  template:
    metadata: { labels: { app: myapp, color: blue } }
    spec:
      containers:
      - name: myapp
        image: karthikg23/myapp:latest
        ports: [{ containerPort: 8080 }]
        env: [{ name: COLOR, value: "blue" }]
